version: "3.1"

services:
  whoami:
    image: "containous/whoami"
    container_name: "simple-pp"
    environment:
      - "VIRTUAL_HOST=SOME_SUB_DOMAIN.MY_DOMAIN_NAME.com"
      - "LETSENCRYPT_HOST=SOME_SUB_DOMAIN.MY_DOMAIN_NAME.com"
    networks:
      - dev
networks:
  dev:
    external: true
